name: Build and Deploy to ECS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: three-tier-cluster
  ECS_SERVICE: three-tier-service
  FRONTEND_REPOSITORY: three-tier-frontend
  BACKEND_REPOSITORY: three-tier-backend

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ${{ env.AWS_REGION }}


      - name: Login to Amazon ECR

        id: login-ecr

        uses: aws-actions/amazon-ecr-login@v2


      - name: Build and push frontend

        run: |

          docker build \
            -t $FRONTEND_REPOSITORY \
            ./frontend

          docker tag \
            $FRONTEND_REPOSITORY:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/$FRONTEND_REPOSITORY:latest

          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/$FRONTEND_REPOSITORY:latest


      - name: Build and push backend

        run: |

          docker build \
            -t $BACKEND_REPOSITORY \
            ./backend

          docker tag \
            $BACKEND_REPOSITORY:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/$BACKEND_REPOSITORY:latest

          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/$BACKEND_REPOSITORY:latest


      - name: Deploy new images

        run: |

          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment


      - name: Wait for deployment

        run: |

          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE
